# Generated by Django 4.1 on 2022-08-23 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('premier', models.CharField(max_length=40)),
                ('image', models.ImageField(height_field=257, upload_to='', width_field=180)),
            ],
        ),
        migrations.CreateModel(
            name='Peliculas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('synopsis', models.CharField(max_length=600)),
                ('year', models.IntegerField()),
                ('gener', models.CharField(max_length=40)),
                ('image', models.ImageField(upload_to='')),
                ('trailer', models.URLField()),
                ('rating', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Plataformas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('link', models.URLField()),
            ],
        ),
    ]
