# Generated by Django 4.1 on 2022-08-23 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peliculas',
            name='image',
            field=models.ImageField(null=True, upload_to='imagenes'),
        ),
    ]
