# Generated by Django 4.1 on 2022-08-25 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0004_alter_news_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peliculas',
            name='rating',
            field=models.FloatField(),
        ),
    ]
