# Generated by Django 4.1 on 2022-08-25 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0005_alter_peliculas_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='plataformas',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
