# Generated by Django 4.1 on 2022-09-20 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0006_plataformas_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=40)),
                ('password', models.CharField(max_length=600)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
