# Generated by Django 4.1 on 2022-09-21 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0007_registro'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Registro',
        ),
        migrations.AlterField(
            model_name='peliculas',
            name='name',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
