# Generated by Django 4.1 on 2022-09-21 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0008_delete_registro_alter_peliculas_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peliculas',
            name='gener',
            field=models.CharField(max_length=40, verbose_name='Género'),
        ),
        migrations.AlterField(
            model_name='peliculas',
            name='image',
            field=models.ImageField(null=True, upload_to='media/', verbose_name='Portada'),
        ),
        migrations.AlterField(
            model_name='peliculas',
            name='name',
            field=models.CharField(max_length=40, unique=True, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='peliculas',
            name='rating',
            field=models.FloatField(verbose_name='Calificación'),
        ),
        migrations.AlterField(
            model_name='peliculas',
            name='synopsis',
            field=models.CharField(max_length=600, verbose_name='Reseña'),
        ),
        migrations.AlterField(
            model_name='peliculas',
            name='trailer',
            field=models.URLField(verbose_name='Trailer'),
        ),
        migrations.AlterField(
            model_name='peliculas',
            name='year',
            field=models.IntegerField(verbose_name='Año'),
        ),
    ]
