# Generated by Django 4.1 on 2022-09-22 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0009_alter_peliculas_gener_alter_peliculas_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peliculas',
            name='image',
            field=models.ImageField(null=True, upload_to='', verbose_name='Portada'),
        ),
    ]
